import = [
  "C:\\Users\\Isaque Diniz\\AppData\\Roaming\\alacritty\\themes\\gruvbox_material_hard_dark.toml"
]

live_config_reload = true

[env]
TERM="xterm-256color"

[shell]
program = "ubuntu"

[window]
decorations = "None"
padding = { x = 10, y = 10 }
dynamic_padding = true
dimensions = { columns = 150, lines = 40 }
position = { x = 0, y = 0 }

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }
size = 15

[cursor]
style = { shape = "Beam", blinking = "On" }

[selection]
save_to_clipboard = true
